version: "3.7"
services:
  laravel_web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel_web
    container_name: laravel-web
    restart: unless-stopped
    working_dir: /app
    ports:
      - "${LARAVEL_PORT}:80"
    volumes:
      - ./:/app
    networks:
      - laravel_net

  laravel_db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - v_laravel_mysql:/var/lib/mysql

    networks:
      - laravel_net


networks:
  laravel_net:
    driver: bridge

volumes:
  v_laravel_redis:
  v_laravel_mysql:
